/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package observer;

import observer.editor.Editor;
import observer.listeners.DifferentNotifyListener;
import observer.listeners.EmailNotificationListener;
import observer.listeners.LogOpenListener;

public class App {

    public static void main(String[] args) {
        Editor editor = new Editor();
        editor.events.subscribe("open", new LogOpenListener("/path/to/log/file.txt"));
        editor.events.subscribe("save", new EmailNotificationListener("admin@example.com"));
        editor.events.subscribe("save", new DifferentNotifyListener(" best text i can think of"));

        try {
            editor.openFile("test.txt");
            editor.saveFile();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
