/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package command;

import command.editor.Editor;

public class App {
    public static void main(String[] args) {
        Editor editor = new Editor();
        editor.init();
    }
}
